### ISSUE TITLE
Broke it - Run time longer than 10s

### ISSUE THREAD

**Issue by jcdickinson** [ashmind/Unbreakable#18]
This takes far longer than 10s to terminate.

```
using System;
using System.Collections.Generic;
using System.Linq;

static class Program {
    static int Run() {
        IEnumerable<string> prev = new string[0];
        for (var i = 0; i < 100; i++)
            prev = prev.Concat(prev);
        string.Join(", ", prev);
        return 0;
    }
}
```

**Comment by jcdickinson** [comment]
Noticed that you added `guard:memory`, the memory guard seems to catch this: using an non-empty array quickly quits with a guard exception.

**Comment by ashmind** [comment]
@jcdickinson You are right -- very cool trick with an empty array.
This is way more interesting than I thought, I might need a new guard for this (enumerable nesting).

**Comment by ashmind** [comment]
Sadly decided to deprecate this library before I ever got to fix this, so unlikely it will ever get fixed unless someone is really keen to contribute. Still, great catch.
